name: Verify file

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
  
jobs:
  verify:  
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_WF == 'true' }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: |
          [[ -f ${{ vars.FILE_TO_CHECK }} ]] || ( echo "${{ vars.FILE_TO_CHECK }} file needs to be added to ${{ github.repository }} !" && exit 1 )
          
      
